-- MySQL Script generated by MySQL Workbench
-- 11/15/17 08:58:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facture_magasin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facture_magasin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facture_magasin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `facture_magasin` ;

-- -----------------------------------------------------
-- Table `facture_magasin`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facture_magasin`.`article` (
  `code` VARCHAR(255) NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  `prix` DOUBLE NOT NULL,
  `categorie` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `designation_UNIQUE` (`designation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facture_magasin`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facture_magasin`.`facture` (
  `num` INT NOT NULL,
  `date_facture` DATETIME NOT NULL,
  PRIMARY KEY (`num`),
  UNIQUE INDEX `num_UNIQUE` (`num` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facture_magasin`.`achat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facture_magasin`.`achat` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `quantite` INT NOT NULL,
  `code_article` VARCHAR(255) NOT NULL,
  `num_facture` INT NOT NULL,
  PRIMARY KEY (`num`),
  UNIQUE INDEX `num_UNIQUE` (`num` ASC),
  INDEX `fk_achat_article_idx` (`code_article` ASC),
  INDEX `fk_achat_facture1_idx` (`num_facture` ASC),
  CONSTRAINT `fk_achat_article`
    FOREIGN KEY (`code_article`)
    REFERENCES `facture_magasin`.`article` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achat_facture1`
    FOREIGN KEY (`num_facture`)
    REFERENCES `facture_magasin`.`facture` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
