/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import minimagasin.Article;
import minimagasin.ArticleEnSolde;
import minimagasin.Categorie;
import minimagasin.CategorieInvalideException;

/**
 *
 * @author Deoel
 */
public class NouvelArticle extends javax.swing.JFrame {

    /**
     * Creates new form NouvelArticle
     */
    public NouvelArticle() {
        initComponents();
        this.lblMessage.setText(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCategorie = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        cbEnSolde = new javax.swing.JCheckBox();
        txtRemise = new javax.swing.JTextField();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("NOUVEL ARTICLE");

        jLabel2.setText("CODE DE L'ARTICLE : ");

        jLabel3.setText("DESIGNATION : ");

        jLabel4.setText("PRIX : ");

        jLabel5.setText("CATEGORIE :");

        cmbCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informatique", "Bureautique" }));

        jButton1.setText("ENREGISTRER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        cbEnSolde.setText("En solde");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbEnSolde)
                        .addGap(18, 18, 18)
                        .addComponent(txtRemise, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(txtCode)
                    .addComponent(txtDesignation)
                    .addComponent(txtPrix)
                    .addComponent(cmbCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEnSolde)
                    .addComponent(txtRemise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(lblMessage)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(!this.txtCode.getText().isEmpty() && !this.txtDesignation.getText().isEmpty() &&
                !this.txtPrix.getText().isEmpty()) {
            try {
                Article article = null;
                if(this.cbEnSolde.isSelected() && !this.txtRemise.getText().isEmpty()) {
                    article = new ArticleEnSolde(Double.valueOf(this.txtRemise.getText()), this.txtCode.getText(),
                        this.txtDesignation.getText(),
                        Double.valueOf(this.txtPrix.getText()), Categorie.valueOf(this.cmbCategorie.getSelectedItem().toString()));
                } else {
                    article = new Article(this.txtCode.getText(),
                        this.txtDesignation.getText(),
                        Double.valueOf(this.txtPrix.getText()), Categorie.valueOf(this.cmbCategorie.getSelectedItem().toString()));
                }
                
                int res = article.enregistrer();

                this.messageArticleEnregristrement(res);

            } catch (CategorieInvalideException ex) {
                ex.printStackTrace();
            }
        } else {
            this.afficherMessage("Données incomplètes!");
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouvelArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouvelArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouvelArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouvelArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouvelArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbEnSolde;
    private javax.swing.JComboBox cmbCategorie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JFormattedTextField txtPrix;
    private javax.swing.JTextField txtRemise;
    // End of variables declaration//GEN-END:variables

    private void messageArticleEnregristrement(int res) {
        if(res != 0) {
            this.txtCode.setText(null);
            this.txtDesignation.setText(null);
            this.txtPrix.setText(null);
            
            this.afficherMessage("Article enregistré!");
        } else {
            this.afficherMessage("Données erronées!");
        }
    }
    
    private void afficherMessage(String message) {
        new Thread(new Runnable() {

            @Override
            public void run() {
                lblMessage.setText(message);
                for (int i = 0; i < 3; i++) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
                lblMessage.setText(null);
            }
        }).start();
    }
}
